canvas=document.getElementById("myCanvas");
ctx=canvas.getContext("2d");
color="red";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(200, 200, 40, 0, 2*Math.PI);
ctx.stroke();
canvas=document.getElementById("myCanvas");
ctx=canvas.getContext("2d");
color="blue";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(275, 200, 40, 0, 2*Math.PI);
ctx.stroke();
canvas=document.getElementById("myCanvas");
ctx=canvas.getContext("2d");
color="black";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(350, 200, 40, 0, 2*Math.PI);
ctx.stroke();
canvas=document.getElementById("myCanvas");
ctx=canvas.getContext("2d");
color="yellow";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(235, 250, 40, 0, 2*Math.PI);
ctx.stroke();
canvas=document.getElementById("myCanvas");
ctx=canvas.getContext("2d");
color="green";
ctx.beginPath();
ctx.strokeStyle=color;
ctx.lineWidth=2;
ctx.arc(315, 250, 40, 0, 2*Math.PI);
ctx.stroke();
ctx.beginPath();
    ctx.strokeStyle="black";
    ctx.lineWidth=2;
    ctx.rect(150,150,450,200);
    ctx.stroke();
